// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using RedePapagaioWebApplication.Connection;

#nullable disable

namespace RedePapagaioWebApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250607231845_TesteMigration")]
    partial class TesteMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedePapagaioWebApplication.Models.AjudaRealizada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AJUDA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAjuda")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_AJUDA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_AJUDA");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OCORRENCIA");

                    b.Property<int>("TipoAjudaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO_AJUDA");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("TipoAjudaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("T_PPG_AJUDA_REALIZADA", (string)null);
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.NivelUrgencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_NIVEL_URGENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NM_NIVEL");

                    b.HasKey("Id");

                    b.ToTable("T_PPG_NIVEL_URGENCIA", (string)null);
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OCORRENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_OCORRENCIA");

                    b.Property<int>("NivelUrgenciaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_NIVEL_URGENCIA");

                    b.Property<int>("RegiaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<int>("StatusOcorrenciaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_STATUS_OCORRENCIA");

                    b.Property<int>("TipoOcorrenciaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO_OCORRENCIA");

                    b.HasKey("Id");

                    b.HasIndex("NivelUrgenciaId");

                    b.HasIndex("RegiaoId");

                    b.HasIndex("StatusOcorrenciaId");

                    b.HasIndex("TipoOcorrenciaId");

                    b.ToTable("T_PPG_OCORRENCIA", (string)null);
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.Regiao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_CIDADE");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_ESTADO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_REGIAO");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_PAIS");

                    b.HasKey("Id");

                    b.ToTable("T_PPG_REGIAO", (string)null);
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.StatusOcorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_STATUS_OCORRENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NM_STATUS");

                    b.HasKey("Id");

                    b.ToTable("T_PPG_STATUS_OCORRENCIA", (string)null);
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TELEFONE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)")
                        .HasColumnName("NR_DDD");

                    b.Property<string>("DDI")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)")
                        .HasColumnName("NR_DDI");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("NR_TELEFONE");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("T_PPG_TELEFONE", (string)null);
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.TipoAjuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO_AJUDA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_TIPO_AJUDA");

                    b.HasKey("Id");

                    b.ToTable("T_PPG_TIPO_AJUDA", (string)null);
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.TipoOcorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO_OCORRENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_TIPO_OCORRENCIA");

                    b.HasKey("Id");

                    b.ToTable("T_PPG_TIPO_OCORRENCIA", (string)null);
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_USUARIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NM_SENHA");

                    b.HasKey("Id");

                    b.ToTable("T_PPG_USUARIO", (string)null);
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.AjudaRealizada", b =>
                {
                    b.HasOne("RedePapagaioWebApplication.Models.Ocorrencia", "Ocorrencia")
                        .WithMany("AjudasRealizadas")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedePapagaioWebApplication.Models.TipoAjuda", "TipoAjuda")
                        .WithMany("AjudasRealizadas")
                        .HasForeignKey("TipoAjudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedePapagaioWebApplication.Models.Usuario", "Usuario")
                        .WithMany("AjudasRealizadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("TipoAjuda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.Ocorrencia", b =>
                {
                    b.HasOne("RedePapagaioWebApplication.Models.NivelUrgencia", "NivelUrgencia")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("NivelUrgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedePapagaioWebApplication.Models.Regiao", "Regiao")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedePapagaioWebApplication.Models.StatusOcorrencia", "StatusOcorrencia")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("StatusOcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedePapagaioWebApplication.Models.TipoOcorrencia", "TipoOcorrencia")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("TipoOcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelUrgencia");

                    b.Navigation("Regiao");

                    b.Navigation("StatusOcorrencia");

                    b.Navigation("TipoOcorrencia");
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.Telefone", b =>
                {
                    b.HasOne("RedePapagaioWebApplication.Models.Usuario", "Usuario")
                        .WithMany("Telefones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.NivelUrgencia", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.Ocorrencia", b =>
                {
                    b.Navigation("AjudasRealizadas");
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.Regiao", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.StatusOcorrencia", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.TipoAjuda", b =>
                {
                    b.Navigation("AjudasRealizadas");
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.TipoOcorrencia", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("RedePapagaioWebApplication.Models.Usuario", b =>
                {
                    b.Navigation("AjudasRealizadas");

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
